[package]
name = "ttrpg-engine"
version = "0.1.0"
description = "Configurable TTRPG engine Tauri v2 application"
authors = ["you"]
edition = "2021"
default-run = "ttrpg-engine"

[lib]
# `cdylib` is required for desktop bundling and Android target
# `staticlib` is required for iOS target
# `rlib` is required for local Rust testing/benchmarking
name = "ttrpg_engine_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rand = "0.10.2"
csv = "1.4.0"
base64 = "0.22"
rusqlite = { version = "0.32", features = ["bundled"] }
